#---------------------------------------------------------------------------
#   Copyright (c) 2014 Bombardier Transportation (Holdings) USA, Inc
#
#  Make File
#
#  Project : Strategic HIDAC Board
#  System  : R179 Software
#
#  Created :
#     31 Jan 2010
#        David Smail @ BT
#  Revised :
##---------------------------------------------------------------------------
#
# Any flags to be used in the compilation of all C programs should
# be listed here.  (Separate each by a space)
#
# CFLAGS for Softscope debugging are:
#    . DEBUG
#    . TYPE
#    . SYMBOLS
#
#   [COMPILER FLAG  Detailed definition]
#
##---------------------------------------------------------------------------
#
# USAGE:
#               make clean
#               make ecam.hex
#
##---------------------------------------------------------------------------

#==================================================================================== 
# Altium/BSO Tasking location
#==================================================================================== 
# Change drive to point at compiler
C166=G:\us\pi\tcctools\Engtools\c16685r1


#==================================================================================== 
# Compiler Definitions
#==================================================================================== 

CMPL=$(C166)\bin\cc166.exe


#==================================================================================== 
# Macro Preprocessor executable path
#==================================================================================== 

MAC=$(C166)\bin\m166.exe


#==================================================================================== 
# Assembler Definitions
#==================================================================================== 

ASSM=$(C166)\bin\a166.exe


#==================================================================================== 
# Include path
#==================================================================================== 

INC_PATH=$(C166)\include
INC_HIDAC_DRV=.\HidacDrv

#==================================================================================== 
# Linker Definitions
#==================================================================================== 

LINK=$(C166)\bin\l166.exe


#==================================================================================== 
# Compiler Options
#==================================================================================== 

# For Car Controller flags, add any -Ddefinitions for any #defines used in the code.

!if $d(BURN_IN)
CCFLAGS = -D_C167 -DBURN_IN
!else if $d(REMOVE_AFTER_TEST)
CCFLAGS = -D_C167 -DREMOVE_AFTER_TEST
!else
CCFLAGS = -D_C167 
!endif


COPTS = -OfOpOI -s -T0 -Ml -x -g -err -w68 -OC -OR -c -O3 -F
# Used to generate a list file for examining assembly output of the complier 
#COPTS = -c -Ml -w91 -w68 -O3 -WaEX -WaPR($*.lst) -x -g -s -err

#==================================================================================== 
# Assembler Options
#==================================================================================== 

AOPT = sg DEBUG SYMB EXTEND


#==================================================================================== 
# Definitions
#==================================================================================== 

RM = del
MV = ren


#====================================================================================
# default .c.obj rules
#====================================================================================

.c.obj :
     $(CMPL) -I$(INC_PATH) -I$(INC_HIDAC_DRV) $(COPTS) $(CCFLAGS) $*.c
#     $(CMPL) -I.. $(COPTS) $*.c
#     $(ASSM) $*.src
#     $(RM)   $*.src	


#====================================================================================
# default .c.obj rules
#====================================================================================

.a66.obj :
     $(MAC)  $*.a66 DEFINE(MODEL, LARGE)  INCLUDEPATH('$(C166)\include')
     $(ASSM) $*.src $(AOPT)
#     $(RM)   $*.src


##===================================================================================
# This is a list of all the files that must be updated to generate a new
# executable.
##===================================================================================

OBJECTS =			\
	cstart.obj		\
	analog.obj      \
	burnin.obj		\
	crc.obj			\
	debug.obj		\
	digital.obj		\
	hexled.obj		\
	hwinit.obj		\
	interupt.obj	\
	ipack.obj       \
	main.obj		\
	ram.obj			\
	spareisr.obj	\
	TaskMVB.obj		\
	Pil_def.obj		\
	Pwm.obj			\
	Version.obj		\
	Mvbvar.obj
  
#==================================================================================== 
# Pointer to libraries
#==================================================================================== 

MVBLIB=..\..\MVB\lib\hidac.lib
LIBS = $(C166)\lib\extp\c166l.lib $(C166)\lib\extp\rt166l.lib $(C166)\lib\extp\fp166l.lib $(MVBLIB)

##===================================================================================
# Link and locate commands
##===================================================================================
LINKROM = $(LINK) LINK @r179.lnk .\hidacdrv\hidac.lno $(LIBS) TO r179.lno
LOCROM =  $(LINK) LOCATE lsy @r179.rom NOCC print(r179.mp2)


#===================== 
# the dependencies       [list the *.h & *.c file dependencies separated by a space]
#=====================

cstart.obj : cstart.a66




#===================== 
# Builds
#=====================


r179.hex : $(OBJECTS) r179.lnk r179.rom makefile
	   $(LINKROM)
	   $(LOCROM)
# -r is needed in order to be compatible with Bombardier C167 FLASH programming tool
        G:\us\pi\tcctools\Engtools\c16685r1\bin\ihex166.exe -r -EFF r179.out r179.hex
        gpcrcg config.crc


r179burn.hex : $(OBJECTS) r179.lnk r179.rom makefile
	   $(LINKROM)
	   $(LOCROM)
# -r is needed in order to be compatible with Bombardier C167 FLASH programming tool
        G:\us\pi\tcctools\Engtools\c16685r1\bin\ihex166.exe -r -EFF r179.out r179.hex
        gpcrcg config.crc
		copy r179crc.hex r179burn.hex
		-$(RM) r179crc.hex

clean : 
		-$(RM) *.obj
		-$(RM) *.lst
		-$(RM) *.err
		-$(RM) *.lno
		-$(RM) *.mp2
		-$(RM) *.map
		-$(RM) *.out
		-$(RM) *.167

